"""Weekly digest — a top-N email summary of recent matches.

Unlike per-scan alerts (which fire on every scan with new matches), the digest
is a single high-signal summary: the best N jobs first seen in the last N days,
ranked by score. Intended to be run on a schedule (e.g. Monday morning) or
manually via ``--digest``.

Pure selection/formatting functions are unit-tested; ``send_digest`` reuses the
``alerts`` SMTP settings.
"""
from __future__ import annotations

import logging
import smtplib
from datetime import UTC, datetime, timedelta
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from localjobscout.config import Settings
from localjobscout.db import Job

logger = logging.getLogger(__name__)


def cutoff_iso(days: int, *, now: datetime | None = None) -> str:
    """Return the ISO timestamp `days` days before now (UTC)."""
    base = now or datetime.now(UTC)
    return (base - timedelta(days=days)).isoformat()


def select_digest_jobs(
    jobs: list[Job],
    *,
    since_iso: str,
    threshold: float,
    top_n: int,
) -> list[Job]:
    """Pick the top_n highest-scoring jobs first seen on/after since_iso.

    Excludes terminal application statuses (applied/rejected/hidden) so the
    digest only surfaces actionable jobs.
    """
    excluded = {"applied", "rejected", "hidden"}
    candidates = [
        j for j in jobs
        if (j.score or 0.0) >= threshold
        and j.first_seen >= since_iso
        and j.application_status not in excluded
    ]
    candidates.sort(key=lambda j: j.score or 0.0, reverse=True)
    return candidates[:top_n]


def _salary_cell(job: Job) -> str:
    if job.salary_min is None and job.salary_max is None:
        return "—"
    lo = f"${job.salary_min:,}" if job.salary_min is not None else "?"
    hi = f"${job.salary_max:,}" if job.salary_max is not None else "?"
    return lo if lo == hi else f"{lo}–{hi}"


def build_digest_html(jobs: list[Job], period_label: str) -> str:
    rows = ""
    for i, job in enumerate(jobs, 1):
        score = f"{job.score:.2f}" if job.score is not None else "—"
        deadline = job.deadline or "—"
        rows += (
            "<tr>"
            f"<td>{i}</td>"
            f"<td>{score}</td>"
            f'<td><a href="{job.url}">{job.title}</a></td>'
            f"<td>{job.company}</td>"
            f"<td>{job.location}</td>"
            f"<td>{_salary_cell(job)}</td>"
            f"<td>{deadline}</td>"
            f"<td>{job.source}</td>"
            "</tr>\n"
        )
    return (
        "<!DOCTYPE html><html><head><style>"
        "table{border-collapse:collapse;width:100%}"
        "th,td{border:1px solid #ddd;padding:6px;text-align:left}"
        "th{background:#3367d6;color:white}"
        "tr:nth-child(even){background:#f5f5f5}"
        "a{color:#1a0dab}"
        "</style></head><body>"
        f"<h2>Your top {len(jobs)} job(s) — {period_label}</h2>"
        "<table><tr>"
        "<th>#</th><th>Score</th><th>Title</th><th>Company</th>"
        "<th>Location</th><th>Salary</th><th>Deadline</th><th>Source</th>"
        f"</tr>\n{rows}</table>"
        "<p style='color:#888;font-size:12px'>"
        "Generated by LocalJobScout. Mark applied with "
        "<code>python -m localjobscout --mark applied &lt;ID&gt;</code>.</p>"
        "</body></html>"
    )


def build_digest_text(jobs: list[Job], period_label: str) -> str:
    lines = [f"Your top {len(jobs)} job(s) — {period_label}", ""]
    for i, job in enumerate(jobs, 1):
        score = f"{job.score:.2f}" if job.score is not None else "—"
        lines.append(f"{i}. [{score}] {job.title} — {job.company}")
        lines.append(f"   {job.location}  ·  {job.source}")
        if job.deadline:
            lines.append(f"   deadline: {job.deadline}")
        lines.append(f"   {job.url}")
        lines.append("")
    return "\n".join(lines)


def send_digest(
    jobs: list[Job],
    settings: Settings,
    period_label: str,
) -> bool:
    """Send the digest via the alerts SMTP settings. Returns True on success.

    Returns False (without raising) when no recipients are configured.
    """
    alerts = settings.alerts
    if not alerts.email_to or not alerts.email_from:
        logger.warning("digest: email_from/email_to not configured in alerts")
        return False
    if not jobs:
        return True

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"LocalJobScout digest — {len(jobs)} jobs ({period_label})"
    msg["From"] = alerts.email_from
    msg["To"] = ", ".join(alerts.email_to)
    msg.attach(MIMEText(build_digest_text(jobs, period_label), "plain", "utf-8"))
    msg.attach(MIMEText(build_digest_html(jobs, period_label), "html", "utf-8"))

    try:
        with smtplib.SMTP(
            alerts.email_smtp_host, alerts.email_smtp_port, timeout=30
        ) as server:
            server.ehlo()
            server.starttls()
            if alerts.email_password:
                server.login(alerts.email_from, alerts.email_password)
            server.sendmail(
                alerts.email_from, alerts.email_to, msg.as_string()
            )
        logger.info("digest sent: %d jobs → %s", len(jobs), alerts.email_to)
        return True
    except (smtplib.SMTPException, OSError) as exc:
        logger.error("digest send failed: %s", exc)
        return False
