"""Persistent markdown export of all matched jobs.

Writes data/matches.md after every scan — a ranked table the user can
open in any text editor or Obsidian to review all-time matches.

Checkbox meaning:
  [ ]  not yet reviewed
  [~]  seen / interested / interviewing
  [x]  applied or offered
  [✗]  rejected
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path

from localjobscout import db as db_module
from localjobscout.config import Settings

_CHECKBOX: dict[str | None, str] = {
    None: "[ ]",
    "seen": "[~]",
    "interested": "[~]",
    "applied": "[x]",
    "interviewed": "[~]",
    "offered": "[x]",
    "rejected": "[✗]",
    "hidden": "[-]",
}


def write_matches_md(settings: Settings) -> Path:
    """Write/overwrite data/matches.md with all above-threshold jobs by score."""
    jobs = db_module.get_recent_jobs(limit=None)
    thr = settings.match_threshold
    matches = sorted(
        [j for j in jobs if (j.score or 0) >= thr],
        key=lambda j: j.score or 0,
        reverse=True,
    )

    out_path = settings.db_path.parent / "matches.md"
    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines: list[str] = [
        "# LocalJobScout — All Matched Jobs",
        "",
        f"> **Updated:** {now}  "
        f"·  **Threshold:** {thr:.2f}  "
        f"·  **{len(matches)} matches**  "
        f"·  {len(jobs)} total in DB",
        ">",
        "> Mark a job:  `tui.bat`  or  "
        "`python -m localjobscout --mark <status> <ID>`",
        "> Statuses: `seen` `interested` `applied` `interviewed` `offered` "
        "`rejected` `hidden`",
        "",
        "| # | Score | ID | ✓ | Title | Company | Location | Source | Link |",
        "|--:|------:|:---|:--|:------|:--------|:---------|:-------|:-----|",
    ]

    for i, job in enumerate(matches, 1):
        st = job.application_status
        checkbox = _CHECKBOX.get(st, "[ ]")
        status_cell = f"{checkbox} {st}" if st else "[ ]"
        short_id = f"`{job.id[:8]}`"
        title = job.title[:55].replace("|", "\\|")
        company = (job.company or "—")[:28].replace("|", "\\|")
        location = (job.location or "—")[:22].replace("|", "\\|")
        link = f"[open]({job.url})"
        lines.append(
            f"| {i} | `{job.score:.3f}` | {short_id} | {status_cell} "
            f"| {title} | {company} | {location} | {job.source} | {link} |"
        )

    lines += [
        "",
        "---",
        "",
        f"*Generated by LocalJobScout · {now}*",
    ]

    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path
